from enum import Enum


class MesaRenderFlag(Enum):
    DISPLAY_HEIGHT_REMAIN = 0
    DISPLAY_HEIGHT_WINDOW = 1
    DISPLAY_HEIGHT_PARENT = 2
    DISPLAY_HEIGHT_PANEL = 3
    DISPLAY_WIDTH_REMAIN = 4
    DISPLAY_WIDTH_WINDOW = 5
    DISPLAY_WIDTH_PARENT = 6
    DISPLAY_WIDTH_PANEL = 7

    CORE_CONTAINER = 8
    SLIDABLE_CONTAINER_VERTICAL = 9
    SLIDABLE_CONTAINER_HORIZONTAL = 10

    TEXT_CENTERED_V = 11
    TEXT_CENTERED_H = 12
    ELEMENT_CENTERED_V = 13
    ELEMENT_CENTERED_H = 14

    IMAGE_CENTERED_V = 15
    IMAGE_CENTERED_H = 16
    FLEXBOX = 17
    GRID = 18
    SINGLE_CONTAINER = 19
