from mesa.style.colors import MesaColors


class MesaDefaultGUI:
    DEFAULT_APP_HEIGHT = 600
    DEFAULT_APP_WIDTH = 360
    DEFAULT_APP_BACKGROUND_COLOR = MesaColors.BLACKBLUE
    DEFAULT_CONTAINER_BACKGROUND_COLOR = MesaColors.DARKBLUE
    DEFAULT_SCENE_BACKGROUND_COLOR = MesaColors.DARKBLUE
    DEFAULT_FONT_SIZE = 16
    DEFAULT_TEXT_INPUT_SIZE = 16
    DEFAULT_FONT_TYPE = "consolas"
    DEFAULT_TEXT_COLOR = MesaColors.ALICEWHITE
    DEFAULT_TEXT_HOVER_COLOR = MesaColors.DARKBLUE
    HEADER_FONT_SIZE = 20
    SECONDARY_FONT_SIZE = 12
